name: deploy

on:
  push:
    tags:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Publish Image to Digital Ocean Container Registry
        shell: bash
        run: |
          doctl registry login --expiry-seconds 600
          docker build . -t registry.digitalocean.com/${{ secrets.REGISTRY }}/${{ secrets.IMAGE }}:${{ github.ref_name }}
          docker push registry.digitalocean.com/${{ secrets.REGISTRY }}/${{ secrets.IMAGE }}:${{ github.ref_name }}

      - name: DigitalOcean App Platform deployment
        uses: digitalocean/app_action@main
        with:
          app_name: ${{ secrets.APP_NAME }}
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          images: '[{
            "name": "${{ secrets.COMPONENT_NAME }}",
            "repository": "registry.digitalocean.com/${{ secrets.REGISTRY }}/${{ secrets.IMAGE }}",
            "tag": "${{ github.ref_name }}"
            }
            ]'
